import React, { useMemo, useState } from 'react';
import { ReductionAction } from '../types';
import { solveCarbonBudgetAllocation } from '../utils/pulpSolver';
import { CircleHelp, PlusCircle, SlidersHorizontal, Trash2 } from 'lucide-react';

interface BudgetOptimizerViewProps {
  actions: ReductionAction[];
  onActionsChange: React.Dispatch<React.SetStateAction<ReductionAction[]>>;
  budget: string;
  onBudgetChange: React.Dispatch<React.SetStateAction<string>>;
}

export const BudgetOptimizerView: React.FC<BudgetOptimizerViewProps> = ({ actions, onActionsChange, budget, onBudgetChange }) => {
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [cost, setCost] = useState(''); const [savedTons, setSavedTons] = useState(''); const [durationYears, setDurationYears] = useState('10'); const [templateId, setTemplateId] = useState(''); const [estimateNote, setEstimateNote] = useState('');
  const result = useMemo(() => solveCarbonBudgetAllocation(actions, Number(budget) || 0), [actions, budget]);
  const applyTemplate = (id: string) => { setTemplateId(id); const template = PROJECT_TEMPLATES.find((item) => item.id === id); if (!template) { setEstimateNote(''); return; } setName(template.name); setCategory(template.category); setDescription(template.description); setDurationYears(String(template.lifetimeYears)); setSavedTons(String(template.starterAnnualTons)); setEstimateNote(`Auto-estimated ${template.starterAnnualTons} tCO₂e/year for a representative project. ${template.assumption}`); };
  const addProject = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !cost || !savedTons) return; onActionsChange((current) => [...current, { id: `project_${Date.now()}`, actionName: name.trim(), description: description.trim(), category: category.trim() || 'Uncategorized', cost: Number(cost), co2SavedTonsPerYear: Number(savedTons), implementationDurationYears: Math.max(1, Number(durationYears) || 10), icon: 'project' }]); setName(''); setDescription(''); setCategory(''); setCost(''); setSavedTons(''); setDurationYears('10'); setTemplateId(''); setEstimateNote(''); };
  const selected = new Set(result.selectedIds);
  return <div className="w-full max-w-4xl mx-auto space-y-6 pb-12 animate-fade-in">
    <div className="pt-2"><h1 className="text-xl sm:text-2xl font-bold text-[#F5F6F7]">Budget optimizer</h1><p className="text-sm text-[#9CA3AF] mt-1">Add your possible reduction projects, then enter a budget to find the highest-emission-reduction combination.</p></div>
    <div className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><label className="block text-xs text-[#9CA3AF] font-medium mb-1.5">Available budget (₹)</label><input className="input" type="number" min="0" step="any" value={budget} onChange={(e) => onBudgetChange(e.target.value)} placeholder="Enter your available budget" /></div>
    <section className="rounded-2xl border border-[#34D399]/30 bg-[#34D399]/5 p-4"><div className="flex gap-3"><CircleHelp className="w-5 h-5 shrink-0 text-[#34D399] mt-0.5" /><div><h2 className="font-semibold text-sm">How this page works</h2><p className="mt-1 text-sm text-[#C5CDD6]">Add projects you could implement, then enter your budget. The recommended portfolio is the best combination that fits within that budget and has the highest combined annual CO₂ reduction. It is a planning recommendation—not proof that a project has been installed.</p></div></div></section>
    <form onSubmit={addProject} className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6 space-y-4"><div><h2 className="font-semibold">Add a reduction project</h2><p className="mt-1 text-xs text-[#9CA3AF]">Choose a real-world project type to prefill the form. A web-informed preliminary annual reduction is added automatically and stays editable.</p></div><Field label="Project type (optional template)"><select className="input" value={templateId} onChange={(e) => applyTemplate(e.target.value)}><option value="">Custom project</option>{PROJECT_TEMPLATES.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></Field><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Project name"><input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Replace old motors" required /></Field><Field label="Category (optional)"><input className="input" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="e.g. Energy efficiency" /></Field><Field label="Project cost (₹)"><input className="input" type="number" min="0" value={cost} onChange={(e) => setCost(e.target.value)} placeholder="Enter your assessed project cost" required /></Field><Field label="Annual CO₂ reduction estimate (tCO₂e)"><input className="input" type="number" min="0" step="any" value={savedTons} onChange={(e) => { setSavedTons(e.target.value); setEstimateNote('Edited estimate — verify with site energy, fuel, or feedstock data before relying on it.'); }} placeholder="Select a template to auto-estimate" required />{estimateNote && <p className="text-[11px] leading-4 text-[#FBBF24] mt-1.5">{estimateNote}</p>}</Field><Field label="Reduction lifetime (years)"><input className="input" type="number" min="1" step="1" value={durationYears} onChange={(e) => setDurationYears(e.target.value)} placeholder="e.g. 10" required /></Field></div><Field label="Description (optional)"><textarea className="input min-h-20" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Add equipment, fuel, site assumptions, or measurement notes." /></Field><button className="px-5 py-2.5 rounded-lg bg-[#34D399] text-[#003825] text-sm font-semibold"><PlusCircle className="inline w-4 h-4 mr-1.5" />Add project</button></form>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex items-center gap-2"><SlidersHorizontal className="w-5 h-5 text-[#34D399]" /><div><h2 className="font-semibold">Recommended portfolio</h2><p className="text-xs text-[#9CA3AF] mt-1">Projects highlighted below are selected because, together, they provide the largest annual reduction without exceeding your budget.</p></div></div>{!budget || actions.length === 0 ? <p className="text-sm text-[#9CA3AF] mt-3">Enter a budget and add at least one project to calculate the recommendation.</p> : <div className="mt-4 space-y-4"><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm"><Stat label="Selected projects" value={String(result.selectedIds.length)} /><Stat label="Cost used" value={`₹${result.totalCost.toLocaleString('en-IN')}`} /><Stat label="Annual reduction" value={`${result.totalCo2Saved} tCO₂e`} /><Stat label="Budget left" value={`₹${result.budgetRemaining.toLocaleString('en-IN')}`} /></div>{result.selectedIds.length > 0 && <PortfolioImpact annualTons={result.totalCo2Saved} />}</div>}</section>
    {actions.length > 0 && <section><h2 className="text-base font-semibold mb-3">Your projects ({actions.length})</h2><div className="space-y-2">{actions.map((action) => <div key={action.id} className={`rounded-xl border p-4 ${selected.has(action.id) && budget ? 'border-[#34D399]/60 bg-[#34D399]/5' : 'border-[#26292F] bg-[#16181C]'}`}><div className="flex justify-between items-center gap-3"><div><p className="font-medium">{action.actionName}</p><p className="text-xs text-[#9CA3AF] mt-1">{action.category} · ₹{action.cost.toLocaleString('en-IN')} · {action.co2SavedTonsPerYear} tCO₂e/year · {action.implementationDurationYears || 10}-year lifetime</p></div><button type="button" onClick={() => onActionsChange((current) => current.filter((item) => item.id !== action.id))} aria-label="Delete project"><Trash2 className="w-4 h-4 text-[#9CA3AF] hover:text-red-400" /></button></div>{selected.has(action.id) && budget && <ProjectImpact action={action} />}</div>)}</div></section>}
  </div>;
};
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block text-xs text-[#9CA3AF] font-medium space-y-1.5"><span>{label}</span>{children}</label>;
const Stat = ({ label, value }: { label: string; value: string }) => <div className="rounded-lg bg-[#0B0D10] border border-[#26292F] p-3"><p className="text-[11px] text-[#9CA3AF]">{label}</p><p className="mt-1 font-mono font-semibold text-[#F5F6F7]">{value}</p></div>;
const periodValue = (annualTons: number, days: number) => annualTons * days / 365;
const ImpactGrid = ({ annualTons, lifetimeYears }: { annualTons: number; lifetimeYears?: number }) => <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-xs"><Stat label="1 day" value={`${periodValue(annualTons, 1).toFixed(3)} t`} /><Stat label="1 week" value={`${periodValue(annualTons, 7).toFixed(3)} t`} /><Stat label="1 month" value={`${periodValue(annualTons, 30).toFixed(2)} t`} /><Stat label="1 year" value={`${annualTons.toFixed(2)} t`} />{lifetimeYears && <Stat label={`${lifetimeYears}-year life`} value={`${(annualTons * lifetimeYears).toFixed(2)} t`} />}</div>;
const PortfolioImpact = ({ annualTons }: { annualTons: number }) => <div className="rounded-xl bg-[#0B0D10] border border-[#34D399]/30 p-4"><p className="text-sm font-medium text-[#34D399]">Default portfolio CO₂ reduction by time period</p><p className="text-xs text-[#9CA3AF] mt-1 mb-3">Assumes projects operate consistently after installation.</p><ImpactGrid annualTons={annualTons} /></div>;
const ProjectImpact = ({ action }: { action: ReductionAction }) => <div className="mt-4 pt-4 border-t border-[#34D399]/20"><p className="text-xs font-medium text-[#34D399] mb-2">Optimized-project CO₂ reduction by time period</p><ImpactGrid annualTons={action.co2SavedTonsPerYear} lifetimeYears={action.implementationDurationYears || 10} /></div>;
const PROJECT_TEMPLATES = [
  { id: 'biogas', name: 'Biogas / renewable natural gas from organic waste', category: 'Low-carbon fuel', lifetimeYears: 15, starterAnnualTons: 150, assumption: 'Assumes a small-to-medium organic-waste or wastewater biogas system displacing fossil fuel; methane leakage can materially change the result.', description: 'Capture and use biogas from organic waste or wastewater to displace fossil fuel. Confirm feedstock availability, methane leakage controls, and avoided fuel baseline.' },
  { id: 'solar', name: 'Rooftop solar PV', category: 'Renewable electricity', lifetimeYears: 25, starterAnnualTons: 45, assumption: 'Assumes a small commercial rooftop installation and a grid-displacement calculation; use actual generation and your verified grid factor.', description: 'Generate on-site renewable electricity to reduce grid purchases. Use site-specific generation and grid-emission-factor assumptions.' },
  { id: 'vfd', name: 'Variable-frequency drives for motors and pumps', category: 'Energy efficiency', lifetimeYears: 12, starterAnnualTons: 30, assumption: 'Assumes a targeted motor or pump retrofit with variable load; meter the relevant equipment to validate.', description: 'Match motor and pump speed to demand; verify operating hours, load profile, and metered energy baseline.' },
  { id: 'waste-heat', name: 'Waste-heat recovery', category: 'Energy efficiency', lifetimeYears: 15, starterAnnualTons: 80, assumption: 'Assumes recoverable heat reliably displaces purchased fuel; temperature, uptime, and load matching determine the final rate.', description: 'Recover usable process heat to displace purchased fuel or electricity. Validate temperature, load match, and availability.' },
  { id: 'heat-pump', name: 'Industrial heat pump for low-temperature heat', category: 'Electrification', lifetimeYears: 15, starterAnnualTons: 60, assumption: 'Assumes low-temperature process heat and efficient operation; compare displaced-fuel emissions against added electricity emissions.', description: 'Electrify suitable low-temperature process heat. Compare electricity emissions with the displaced fuel and account for COP.' },
  { id: 'led', name: 'LED lighting and smart controls', category: 'Energy efficiency', lifetimeYears: 10, starterAnnualTons: 15, assumption: 'Assumes a commercial lighting retrofit with regular operating hours; validate against fixture inventory and run hours.', description: 'Replace inefficient lighting and add occupancy/daylight controls. Use fixture hours and metered or calculated electricity savings.' },
  { id: 'compressed-air', name: 'Compressed-air leak repair and pressure optimization', category: 'Energy efficiency', lifetimeYears: 5, starterAnnualTons: 20, assumption: 'Assumes a measured leak-repair programme with compressor energy savings; verify through before-and-after metering.', description: 'Repair leaks and reduce excess pressure; use compressor metering before and after implementation.' },
  { id: 'electrify-fleet', name: 'Electric fleet / material-handling equipment', category: 'Transport electrification', lifetimeYears: 10, starterAnnualTons: 30, assumption: 'Assumes replacement of regularly used fuel-powered material-handling equipment; charging mix and utilization determine the final rate.', description: 'Replace eligible fuel-powered fleet or forklifts with electric alternatives. Compare fuel consumption with charging electricity.' },
  { id: 'biomass', name: 'Sustainable biomass boiler fuel switch', category: 'Low-carbon fuel', lifetimeYears: 15, starterAnnualTons: 100, assumption: 'Assumes sustainable feedstock displaces eligible fossil thermal fuel; lifecycle emissions and local air requirements must be checked.', description: 'Replace eligible fossil thermal fuel with sustainably sourced biomass. Verify feedstock lifecycle emissions and local air-quality requirements.' },
];
