import React, { useMemo, useState } from 'react';
import { ReductionAction } from '../types';
import { solveCarbonBudgetAllocation } from '../utils/pulpSolver';
import { PlusCircle, SlidersHorizontal, Trash2 } from 'lucide-react';

interface BudgetOptimizerViewProps {
  actions: ReductionAction[];
  onActionsChange: React.Dispatch<React.SetStateAction<ReductionAction[]>>;
  budget: string;
  onBudgetChange: React.Dispatch<React.SetStateAction<string>>;
}

export const BudgetOptimizerView: React.FC<BudgetOptimizerViewProps> = ({ actions, onActionsChange, budget, onBudgetChange }) => {
  const [name, setName] = useState(''); const [category, setCategory] = useState(''); const [cost, setCost] = useState(''); const [savedTons, setSavedTons] = useState(''); const [durationYears, setDurationYears] = useState('10');
  const result = useMemo(() => solveCarbonBudgetAllocation(actions, Number(budget) || 0), [actions, budget]);
  const addProject = (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !cost || !savedTons) return; onActionsChange((current) => [...current, { id: `project_${Date.now()}`, actionName: name.trim(), description: '', category: category.trim() || 'Uncategorized', cost: Number(cost), co2SavedTonsPerYear: Number(savedTons), implementationDurationYears: Math.max(1, Number(durationYears) || 10), icon: 'project' }]); setName(''); setCategory(''); setCost(''); setSavedTons(''); setDurationYears('10'); };
  const selected = new Set(result.selectedIds);
  return <div className="w-full max-w-4xl mx-auto space-y-6 pb-12 animate-fade-in">
    <div className="pt-2"><h1 className="text-xl sm:text-2xl font-bold text-[#F5F6F7]">Budget optimizer</h1><p className="text-sm text-[#9CA3AF] mt-1">Add your possible reduction projects, then enter a budget to find the highest-emission-reduction combination.</p></div>
    <div className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><label className="block text-xs text-[#9CA3AF] font-medium mb-1.5">Available budget (₹)</label><input className="input" type="number" min="0" step="any" value={budget} onChange={(e) => onBudgetChange(e.target.value)} placeholder="Enter your available budget" /></div>
    <form onSubmit={addProject} className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6 space-y-4"><h2 className="font-semibold">Add a reduction project</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Project name"><input className="input" value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. Replace old motors" required /></Field><Field label="Category (optional)"><input className="input" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="e.g. Energy efficiency" /></Field><Field label="Project cost (₹)"><input className="input" type="number" min="0" value={cost} onChange={(e) => setCost(e.target.value)} placeholder="Enter project cost" required /></Field><Field label="Expected annual CO₂ reduction (tCO₂e)"><input className="input" type="number" min="0" step="any" value={savedTons} onChange={(e) => setSavedTons(e.target.value)} placeholder="Enter expected annual reduction" required /></Field><Field label="Reduction lifetime (years)"><input className="input" type="number" min="1" step="1" value={durationYears} onChange={(e) => setDurationYears(e.target.value)} placeholder="e.g. 10" required /></Field></div><button className="px-5 py-2.5 rounded-lg bg-[#34D399] text-[#003825] text-sm font-semibold"><PlusCircle className="inline w-4 h-4 mr-1.5" />Add project</button></form>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex items-center gap-2"><SlidersHorizontal className="w-5 h-5 text-[#34D399]" /><h2 className="font-semibold">Recommended portfolio</h2></div>{!budget || actions.length === 0 ? <p className="text-sm text-[#9CA3AF] mt-3">Enter a budget and add at least one project to calculate the recommendation.</p> : <div className="mt-4"><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm"><Stat label="Selected projects" value={String(result.selectedIds.length)} /><Stat label="Cost used" value={`₹${result.totalCost.toLocaleString('en-IN')}`} /><Stat label="Annual reduction" value={`${result.totalCo2Saved} tCO₂e`} /><Stat label="Budget left" value={`₹${result.budgetRemaining.toLocaleString('en-IN')}`} /></div></div>}</section>
    {actions.length > 0 && <section><h2 className="text-base font-semibold mb-3">Your projects ({actions.length})</h2><div className="space-y-2">{actions.map((action) => <div key={action.id} className={`flex justify-between items-center rounded-xl border p-4 ${selected.has(action.id) && budget ? 'border-[#34D399]/60 bg-[#34D399]/5' : 'border-[#26292F] bg-[#16181C]'}`}><div><p className="font-medium">{action.actionName}</p><p className="text-xs text-[#9CA3AF] mt-1">{action.category} · ₹{action.cost.toLocaleString('en-IN')} · {action.co2SavedTonsPerYear} tCO₂e/year · {action.implementationDurationYears || 10}-year lifetime</p></div><button type="button" onClick={() => onActionsChange((current) => current.filter((item) => item.id !== action.id))} aria-label="Delete project"><Trash2 className="w-4 h-4 text-[#9CA3AF] hover:text-red-400" /></button></div>)}</div></section>}
  </div>;
};
const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="block text-xs text-[#9CA3AF] font-medium space-y-1.5"><span>{label}</span>{children}</label>;
const Stat = ({ label, value }: { label: string; value: string }) => <div className="rounded-lg bg-[#0B0D10] border border-[#26292F] p-3"><p className="text-[11px] text-[#9CA3AF]">{label}</p><p className="mt-1 font-mono font-semibold text-[#F5F6F7]">{value}</p></div>;
