import React, { useMemo, useState } from 'react';
import { ActivityLogEntry, ReductionAction, UserProfile } from '../types';
import { solveCarbonBudgetAllocation } from '../utils/pulpSolver';
import { fetchGroqReportSummary } from '../services/groqService';
import { BarChart3, Bot, CalendarClock, CheckCircle2, FileText, Lightbulb, Sparkles, Target, TrendingDown } from 'lucide-react';

interface ReportsViewProps { logs: ActivityLogEntry[]; actions: ReductionAction[]; budget: number; user: UserProfile | null; }
type Horizon = { label: string; days: number; };
const horizons: Horizon[] = [{ label: '1 day', days: 1 }, { label: '1 week', days: 7 }, { label: '1 month', days: 30 }, { label: '1 year', days: 365 }];
const fmt = (value: number, digits = 2) => value.toLocaleString('en-IN', { maximumFractionDigits: digits });

export const ReportsView: React.FC<ReportsViewProps> = ({ logs, actions, budget, user }) => {
  const [summary, setSummary] = useState(''); const [isGenerating, setIsGenerating] = useState(false);
  const report = useMemo(() => buildReport(logs, actions, budget), [logs, actions, budget]);
  const createSummary = async () => { setIsGenerating(true); const response = await fetchGroqReportSummary({ facility: user?.facility || 'Your facility', ...report }); setSummary(response.success ? cleanSummaryText(response.summary) : `AI summary unavailable: ${response.error || 'Add GROQ_API_KEY and try again.'}`); setIsGenerating(false); };
  return <div className="w-full max-w-5xl mx-auto space-y-6 pb-12 animate-fade-in"><Header />
    {!logs.length && <section className="rounded-2xl border border-[#FBBF24]/30 bg-[#FBBF24]/5 p-4 flex gap-3"><FileText className="w-5 h-5 shrink-0 text-[#FBBF24] mt-0.5" /><div><h2 className="font-semibold text-sm">Waiting for verified activity data</h2><p className="mt-1 text-sm text-[#C5CDD6]">The report structure and optimizer comparison are ready. Add activity records to calculate your facility's actual baseline and CO₂e rate.</p></div></section>}
    <section className="grid grid-cols-1 sm:grid-cols-3 gap-3"><Metric label="Observed emissions" value={`${fmt(report.totalKg / 1000)} tCO₂e`} detail={`${logs.length} activity record${logs.length === 1 ? '' : 's'}`} icon={<BarChart3 className="w-5 h-5" />} /><Metric label="Daily run-rate" value={`${fmt(report.dailyKg / 1000)} tCO₂e/day`} detail="Derived from log dates" icon={<CalendarClock className="w-5 h-5" />} /><Metric label="Optimized annual reduction" value={`${fmt(report.annualSavingsTons)} tCO₂e`} detail={report.selectedActions.length ? `${report.selectedActions.length} selected project${report.selectedActions.length === 1 ? '' : 's'}` : 'Set a budget to select projects'} icon={<TrendingDown className="w-5 h-5" />} /></section>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex items-center gap-2"><Target className="w-5 h-5 text-[#34D399]" /><div><h2 className="font-semibold">CO₂e forecast: before vs. after implementation</h2><p className="text-xs text-[#9CA3AF] mt-1">Before = observed run-rate. After = before emissions minus the portfolio reduction selected by Budget Optimizer.</p></div></div><EmissionComparisonChart scenarios={report.scenarios} /><div className="mt-5 grid grid-cols-1 md:grid-cols-4 gap-3">{report.scenarios.map((item) => <div key={item.label} className="rounded-xl bg-[#0B0D10] border border-[#26292F] p-4"><p className="text-sm font-semibold">{item.label}</p><p className="mt-3 text-[11px] text-[#9CA3AF] uppercase tracking-wide">Before → after</p><p className="text-lg font-mono font-semibold">{fmt(item.beforeKg / 1000)} <span className="text-[#9CA3AF]">→</span> <span className="text-[#34D399]">{fmt(item.afterKg / 1000)}</span></p><p className="mt-2 text-xs text-[#34D399]">Avoided: {fmt(item.avoidedKg / 1000)} tCO₂e ({fmt(item.reductionPercent, 1)}%)</p></div>)}</div></section>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex items-center gap-2"><CheckCircle2 className="w-5 h-5 text-[#34D399]" /><div><h2 className="font-semibold">Budget optimizer activity</h2><p className="text-xs text-[#9CA3AF] mt-1">Selected projects are evaluated using the budget set in Budget Optimizer.</p></div></div>{report.selectedActions.length ? <div className="mt-4 space-y-2">{report.selectedActions.map((action) => <div key={action.id} className="rounded-xl bg-[#0B0D10] border border-[#26292F] p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2"><div><p className="font-medium text-sm">{action.actionName}</p><p className="text-xs text-[#9CA3AF] mt-1">Expected to continue for {action.implementationDurationYears || 10} years · {fmt(action.co2SavedTonsPerYear)} tCO₂e/year</p></div><p className="text-sm font-mono text-[#34D399]">₹{fmt(action.cost / Math.max(action.co2SavedTonsPerYear, 0.001), 0)}/tCO₂e</p></div>)}<p className="pt-2 text-xs text-[#9CA3AF]">Portfolio: ₹{fmt(report.totalCost, 0)} invested for {fmt(report.annualSavingsTons)} tCO₂e/year over a weighted average {fmt(report.averageDuration, 1)}-year lifetime.</p></div> : <p className="mt-4 text-sm text-[#9CA3AF]">Set a budget that can fund one or more projects to include an optimizer impact forecast.</p>}</section>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex items-center gap-2"><Lightbulb className="w-5 h-5 text-[#FBBF24]" /><div><h2 className="font-semibold">Lowest-cost reduction suggestions</h2><p className="text-xs text-[#9CA3AF] mt-1">Prioritized from your portfolio and evidence-informed industrial efficiency guidance found via DuckDuckGo.</p></div></div><div className="mt-4 space-y-3">{report.suggestions.map((suggestion) => <div key={suggestion.title} className="rounded-xl bg-[#0B0D10] border border-[#26292F] p-4"><p className="font-medium text-sm">{suggestion.title}</p><p className="text-sm text-[#9CA3AF] mt-1">{suggestion.body}</p>{suggestion.href && <a className="inline-block mt-2 text-xs text-[#34D399] hover:underline" href={suggestion.href} target="_blank" rel="noreferrer">Evidence source ↗</a>}</div>)}</div></section>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="flex items-center gap-2"><Bot className="w-5 h-5 text-[#34D399]" /><div><h2 className="font-semibold">Groq executive summary</h2><p className="text-xs text-[#9CA3AF] mt-1">Summarizes only the computed report values and recommendations.</p></div></div><button onClick={createSummary} disabled={isGenerating} className="px-4 py-2 rounded-lg bg-[#34D399] text-[#003825] text-sm font-semibold disabled:opacity-50"><Sparkles className="inline w-4 h-4 mr-1.5" />{isGenerating ? 'Generating…' : 'Generate summary'}</button></div>{summary && <p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#D1D5DB]">{summary}</p>}</section>
    <section className="rounded-2xl bg-[#16181C] border border-[#26292F] p-5 sm:p-6"><h2 className="font-semibold">Audit checklist</h2><p className="mt-1 text-xs text-[#9CA3AF]">Keep these records with the report so savings can be validated after implementation.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="text-left text-xs text-[#9CA3AF]"><tr><th className="pb-2 font-medium">Control</th><th className="pb-2 font-medium">Evidence</th><th className="pb-2 font-medium">Status</th></tr></thead><tbody className="divide-y divide-[#26292F]"><tr><td className="py-3">Baseline completeness</td><td className="py-3 text-[#9CA3AF]">Activity records, meter totals, and source factors</td><td className="py-3 text-[#FBBF24]">{logs.length ? 'Ready to review' : 'Needs activity data'}</td></tr><tr><td className="py-3">Project savings</td><td className="py-3 text-[#9CA3AF]">Pre/post readings, operating hours, and assumptions</td><td className="py-3 text-[#FBBF24]">Verify after implementation</td></tr><tr><td className="py-3">Budget decision</td><td className="py-3 text-[#9CA3AF]">Selected portfolio and cost per tCO₂e</td><td className="py-3 text-[#34D399]">{report.selectedActions.length ? 'Portfolio recorded' : 'Set optimizer budget'}</td></tr></tbody></table></div></section>
  </div>;
};
type Scenario = { label: string; beforeKg: number; afterKg: number; avoidedKg: number; reductionPercent: number; };
// The API requests plain text, but clean residual Markdown defensively so the
// report never exposes formatting tokens such as ** to users.
const cleanSummaryText = (value: string) => value
  .replace(/\*\*(.*?)\*\*/g, '$1')
  .replace(/__(.*?)__/g, '$1')
  .replace(/^#{1,6}\s*/gm, '')
  .replace(/^\*\s+/gm, '• ')
  .replace(/`([^`]+)`/g, '$1');
const EmissionComparisonChart = ({ scenarios }: { scenarios: Scenario[] }) => {
  const maximum = Math.max(1, ...scenarios.flatMap((item) => [item.beforeKg, item.afterKg]));
  return <div className="mt-6"><div className="flex items-center gap-4 text-xs text-[#9CA3AF]"><span className="flex items-center gap-1.5"><i className="w-2.5 h-2.5 rounded-sm bg-[#94A3B8]" />Before</span><span className="flex items-center gap-1.5"><i className="w-2.5 h-2.5 rounded-sm bg-[#34D399]" />After</span></div><svg viewBox="0 0 720 260" className="w-full h-auto mt-3" role="img" aria-label="Grouped bar chart showing CO2 emissions before and after planned projects for daily, weekly, monthly and annual periods"><line x1="52" x2="700" y1="210" y2="210" stroke="#374151" />{[50, 100, 150, 200].map((y) => <line key={y} x1="52" x2="700" y1={y} y2={y} stroke="#26292F" />)}{scenarios.map((item, index) => { const x = 95 + index * 158; const beforeHeight = item.beforeKg / maximum * 160; const afterHeight = item.afterKg / maximum * 160; return <g key={item.label}><rect x={x} y={210 - beforeHeight} width="42" height={beforeHeight} rx="4" fill="#94A3B8" /><rect x={x + 48} y={210 - afterHeight} width="42" height={afterHeight} rx="4" fill="#34D399" /><text x={x + 45} y="235" fill="#9CA3AF" fontSize="12" textAnchor="middle">{item.label}</text><text x={x + 45} y={Math.max(20, 202 - Math.max(beforeHeight, afterHeight))} fill="#D1D5DB" fontSize="10" textAnchor="middle">{fmt(item.beforeKg / 1000)} t</text></g>; })}</svg></div>;
};
function buildReport(logs: ActivityLogEntry[], actions: ReductionAction[], budget: number) { const totalKg = logs.reduce((sum, item) => sum + Math.max(0, item.calculatedEmissionsKg || 0), 0); const timestamps = logs.map((item) => new Date(item.loggedAt).getTime()).filter(Number.isFinite); const observedDays = timestamps.length > 1 ? Math.max(1, Math.ceil((Math.max(...timestamps) - Math.min(...timestamps)) / 86400000) + 1) : 1; const dailyKg = totalKg / observedDays; const allocation = solveCarbonBudgetAllocation(actions, budget); const selectedActions = actions.filter((action) => allocation.selectedIds.includes(action.id)); const annualSavingsTons = selectedActions.reduce((sum, action) => sum + action.co2SavedTonsPerYear, 0); const scenarios = horizons.map(({ label, days }) => { const beforeKg = dailyKg * days; const avoidedKg = Math.min(beforeKg, annualSavingsTons * 1000 * days / 365); return { label, days, beforeKg, avoidedKg, afterKg: beforeKg - avoidedKg, reductionPercent: beforeKg ? avoidedKg / beforeKg * 100 : 0 }; }); const sortedActions = [...actions].filter((action) => action.co2SavedTonsPerYear > 0).sort((a, b) => a.cost / a.co2SavedTonsPerYear - b.cost / b.co2SavedTonsPerYear); const suggestions: Array<{ title: string; body: string; href?: string }> = [...sortedActions.slice(0, 2).map((action) => ({ title: `Fund ${action.actionName} first`, body: `It has the lowest cost in your entered portfolio at about ₹${fmt(action.cost / action.co2SavedTonsPerYear, 0)} per tCO₂e avoided, with an expected ${action.implementationDurationYears || 10}-year operating life.` })), { title: 'Start with measured energy efficiency improvements', body: 'Prioritize controls, maintenance, process optimization, and energy waste reduction before capital-intensive options; quantify results in the next activity-log cycle.', href: 'https://www.energystar.gov/industrial_plants/decarbonizing_industry/energy_efficiency_reduces_industrial_carbon_emissions' }, { title: 'Use efficiency as the first decarbonization layer', body: 'Industrial energy and resource efficiency can cut emissions while reducing operating costs and improving productivity; verify each project with metered baselines.', href: 'https://decarbonization.unido.org/solutions/energy-efficiency/' }]; return { totalKg, dailyKg, observedDays, annualSavingsTons, totalCost: allocation.totalCost, selectedActions, scenarios, averageDuration: selectedActions.length ? selectedActions.reduce((sum, action) => sum + (action.implementationDurationYears || 10), 0) / selectedActions.length : 0, suggestions }; }
const Header = () => <div className="pt-2"><h1 className="text-xl sm:text-2xl font-bold text-[#F5F6F7]">Reports & audit</h1><p className="text-sm text-[#9CA3AF] mt-1">Data-driven emissions forecasts, portfolio impact, and audit recommendations.</p></div>;
const Metric = ({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: React.ReactNode }) => <div className="rounded-xl bg-[#16181C] border border-[#26292F] p-4"><div className="text-[#34D399]">{icon}</div><p className="text-xs text-[#9CA3AF] mt-3">{label}</p><p className="font-mono font-semibold mt-1">{value}</p><p className="text-[11px] text-[#9CA3AF] mt-1">{detail}</p></div>;
